### ISSUE TITLE
4BPP support

### ISSUE THREAD

**Issue by eadmaster** [DerekPascarella/Saturn-15bpp-Graphics-Converter#1]
is there a tool similar to this supporting 4BPP graphics?

I would like to automate the conversion from this:
https://github.com/eadmaster/pcrown/blob/master/signs/aud_hall_jap.bin
to this
https://github.com/eadmaster/pcrown/blob/master/signs/aud_hall_jap.bmp

(image size is 48*11)

**Comment by DerekPascarella** [comment]
Addressed on Discord.
